#!/bin/bash

REPO_ADDRESS=https://git.digipen.edu/projects/autologic
git clone $REPO_ADDRESS ./repo_dir > /dev/null 2>&1
cd ./repo_dir/CodeFriend && poetry install > /dev/null 2>&1 && poetry run pytest
cd ../../ && rm -rf repo_dir/ > /dev/null 2>&1
